package org.vaadin.samples.cafetycoon.ui.dashboard;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalSplitPanel;
import com.vaadin.ui.declarative.Design;
import org.vaadin.samples.cafetycoon.ui.dashboard.SalesOverview;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class DashboardDesign extends HorizontalSplitPanel {
	protected SalesOverview salesOverview;

	public DashboardDesign() {
		Design.read(this);
	}
}
